/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_de_usuario;

import clases_modelo.AccesoAleatorio;
import clases_modelo.Clientes;
import clases_modelo.Cuentas;
import com.google.gson.Gson;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CreacionDeCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CreacionDeCuenta
     */
    public CreacionDeCuenta() {
        initComponents();
        this.setSize(400, 500);
        this.setLocationRelativeTo(null);
    }

    Clientes clienteNuevo = new Clientes();
    Cuentas cuentaNueva = new Cuentas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtSexo = new javax.swing.ButtonGroup();
        rbtCuenta = new javax.swing.ButtonGroup();
        jPanel1 = new interfaces_de_usuario.PlantillaInterfacesPequeñas();
        jLabel1 = new javax.swing.JLabel();
        tbxNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbxDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbxEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dtcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tbxNumTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        btnGuardarCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        tbxUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(getPreferredSize());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre completo");

        tbxNombre.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxNombre.setForeground(new java.awt.Color(0, 0, 0));
        tbxNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nro de documento");

        tbxDocumento.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxDocumento.setForeground(new java.awt.Color(0, 0, 0));
        tbxDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxDocumentoActionPerformed(evt);
            }
        });
        tbxDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxDocumentoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo electrónico");

        tbxEmail.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxEmail.setForeground(new java.awt.Color(0, 0, 0));
        tbxEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxEmailKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de nacimiento");

        dtcFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        dtcFechaNacimiento.setMaxSelectableDate(restarAños(LocalDate.now()));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Número telefónico");

        tbxNumTelefono.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxNumTelefono.setForeground(new java.awt.Color(0, 0, 0));
        tbxNumTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxNumTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxNumTelefonoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");

        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Repetir contraseña");

        jPasswordField2.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Formulario para nuevos clientes");

        btnGuardarCliente.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnGuardarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarCliente.setText("Enviar");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Regresar");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sexo");

        rbtSexo.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jRadioButton1PropertyChange(evt);
            }
        });

        rbtSexo.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setText("Femenino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo de cuenta");

        rbtCuenta.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton3.setText("Corriente");
        jRadioButton3.setAutoscrolls(true);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        rbtCuenta.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton4.setText("Ahorros");
        jRadioButton4.setAutoscrolls(true);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre de usuario");

        tbxUsuario.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxUsuario.setForeground(new java.awt.Color(0, 0, 0));
        tbxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxUsuarioKeyTyped(evt);
            }
        });

        jPanel1.setSize(400,500);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addGap(56, 56, 56)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jRadioButton3)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tbxNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tbxDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tbxEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tbxUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tbxNumTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnGuardarCliente)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(213, 213, 213)
                                            .addComponent(jRadioButton2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(13, 13, 13))))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tbxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dtcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tbxNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10))
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new InicioSesion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        try {
            recogerDatosCliente();
            recogerDatosCuenta();
            BaseDeDatos.contadorParaId++;
            JOptionPane.showMessageDialog(this, "Ha realizado su solicitud con éxito");
            BaseDeDatos.guardarCambios();
            this.setVisible(false);
            new InicioSesion().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CreacionDeCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void recogerDatosCuenta() {
        cuentaNueva.setTipoDeCuenta(rbtCuenta.getSelection().getActionCommand());
        cuentaNueva.setEstado("Pendiente");
        cuentaNueva.setID(BaseDeDatos.contadorParaId);
        cuentaNueva.crearNumeroCuenta();
        BaseDeDatos.sistema.setCuentas(cuentaNueva);
    }

    private void recogerDatosCliente() throws Exception {
        agregarCorreoElectronico();
        agregarDocumentoIdentidad();
        clienteNuevo.setNombre(tbxNombre.getText());
        clienteNuevo.setFechaDeNacimiento(convertirFecha(dtcFechaNacimiento.getDate()));
        clienteNuevo.setSexo(rbtSexo.getSelection().getActionCommand());
        clienteNuevo.setNumeroTelefono(tbxNumTelefono.getText());
        agregarNombreUsuario();
        agregarContraseña();
        clienteNuevo.setID(BaseDeDatos.contadorParaId);
        clienteNuevo.setEstado("Pendiente");
        BaseDeDatos.sistema.añadirCliente(clienteNuevo);
    }

    private void agregarCorreoElectronico() throws Exception {
        String regexEmail = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        Pattern patternEmail = Pattern.compile(regexEmail, Pattern.CASE_INSENSITIVE);
            if (patternEmail.matcher(tbxEmail.getText()).matches()) {
            clienteNuevo.setCorreoElectronico(tbxEmail.getText());
            }
            else {
            JOptionPane.showMessageDialog(this, "Email invalido");
            throw new Exception("Email invalido");
            }
    }

    private void agregarDocumentoIdentidad() throws Exception {
        if (validacionDocumento()) {
            clienteNuevo.setNumeroDeDocumento(tbxDocumento.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Documento invalido");
            throw new Exception("Documento invalido");
        }
    }

    private void agregarNombreUsuario() throws Exception {
        if(validarUsuario())
            clienteNuevo.getCredenciales().setUsuario(tbxUsuario.getText());
        else{
            JOptionPane.showMessageDialog(this, "Nombre de usuario no disponible");
            throw new Exception("Nombre de usuario no disponible");
        }
    }

    private void agregarContraseña() throws Exception {
        if (Arrays.equals(jPasswordField1.getPassword(),jPasswordField2.getPassword()))
           clienteNuevo.getCredenciales().setContraseña(String.valueOf(jPasswordField1.getPassword()));
        else{
            JOptionPane.showMessageDialog(this, "Contraseñas no coinciden");
            throw new Exception("Contraseñas no coinciden");
        }
    }

    private boolean validacionDocumento() {
        boolean salida = true;
        for (int i = 0; i < BaseDeDatos.sistema.cantClientes(); i++) {
            if(tbxDocumento.getText().equals(BaseDeDatos.sistema.getCliente(i).getNumeroDeDocumento())) 
                salida = false;
        }
        return salida;
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setActionCommand("Masculino");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       jRadioButton2.setActionCommand("Femenino");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jRadioButton1PropertyChange
        for (int i = 0; i < jPanel1.getComponentCount(); i++) {
            if(jPanel1.getComponent(i) instanceof javax.swing.JRadioButton JRadioButton)
                JRadioButton.setContentAreaFilled(false);
        }
    }//GEN-LAST:event_jRadioButton1PropertyChange

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jRadioButton4.setActionCommand("Ahorros");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jRadioButton3.setActionCommand("Corriente");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void tbxDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxDocumentoActionPerformed

    private void tbxDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxDocumentoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros || tbxDocumento.getText().length()==10) {
            evt.consume();
        }
    }//GEN-LAST:event_tbxDocumentoKeyTyped

    private void tbxNumTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNumTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros || tbxNumTelefono.getText().length()==10) {
            evt.consume();
        }
        if(tbxNumTelefono.getText().length()!=10) {
          tbxNumTelefono.setForeground(Color.red);  
        }
    }//GEN-LAST:event_tbxNumTelefonoKeyTyped

    private void tbxNumTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNumTelefonoKeyReleased
        if(tbxNumTelefono.getText().length()==10)
            tbxNumTelefono.setForeground(Color.black);
    }//GEN-LAST:event_tbxNumTelefonoKeyReleased

    private void tbxNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNombreKeyTyped
        if (tbxNombre.getText().length() > 50) 
            evt.consume();
    }//GEN-LAST:event_tbxNombreKeyTyped

    private void tbxEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxEmailKeyTyped
        if (tbxEmail.getText().length() > 50) 
            evt.consume();
    }//GEN-LAST:event_tbxEmailKeyTyped

    private void tbxUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxUsuarioKeyTyped
        if (tbxUsuario.getText().length() > 30)
            evt.consume();
    }//GEN-LAST:event_tbxUsuarioKeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        if (jPasswordField1.getPassword().length > 30)
            evt.consume();
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        if (jPasswordField2.getPassword().length > 30)
            evt.consume();
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        BaseDeDatos.guardarCambios();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing
    private LocalDate convertirFecha(Date fecha) {
        return fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    private boolean validarUsuario() {
        boolean salida = true;
        for (int i = 0; i < BaseDeDatos.sistema.cantClientes(); i++) {
            if(tbxUsuario.getText().equals(BaseDeDatos.sistema.getCliente(i).getCredenciales().getUsuario())) 
                salida = false;
        }
        return salida;
    }
    
    private Date restarAños(LocalDate fecha) {
        fecha = fecha.minusYears(18);
        Date fechaSalida = Date.from(fecha.atStartOfDay(ZoneId.systemDefault()).toInstant());
        return fechaSalida;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionDeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionDeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionDeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionDeCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionDeCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCliente;
    private com.toedter.calendar.JDateChooser dtcFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.ButtonGroup rbtCuenta;
    private javax.swing.ButtonGroup rbtSexo;
    private javax.swing.JTextField tbxDocumento;
    private javax.swing.JTextField tbxEmail;
    private javax.swing.JTextField tbxNombre;
    private javax.swing.JTextField tbxNumTelefono;
    private javax.swing.JTextField tbxUsuario;
    // End of variables declaration//GEN-END:variables
}
