/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_de_usuario;

import clases_modelo.Cdt;
import clases_modelo.Clientes;
import clases_modelo.Creditos;
import clases_modelo.Cuentas;
import clases_modelo.TarjetaDeCredito;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static java.time.temporal.ChronoUnit.DAYS;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PanelClientes extends javax.swing.JFrame {

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        this.setContentPane(new PlantillaInterfacesGrandes());
        initComponents();
        actualizarVentana();
        llenarComboTDC();
        llenarComboCreditos();
        llenarComboCdt();
        this.setLocationRelativeTo(null);
    }
    
    Clientes clienteSesionIniciada = BaseDeDatos.sistema.buscarClientePorID(BaseDeDatos.IDsesionIniciada);
    String bienvenida = "Bienvenido " + pronombreSaludo() + clienteSesionIniciada.getNombre();
    ArrayList <Cuentas>cuentasCliente = new ArrayList();
    Cdt cdtSeleccionado;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tagSaldo = new javax.swing.JLabel();
        lbl1NroCuenta = new javax.swing.JLabel();
        lbl1Saldo = new javax.swing.JLabel();
        bienvenidaUsuario = new javax.swing.JLabel();
        tagNroCuenta = new javax.swing.JLabel();
        tagTipoCuenta = new javax.swing.JLabel();
        lbl1TipoCuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl2NroCuenta = new javax.swing.JLabel();
        lbl2Saldo = new javax.swing.JLabel();
        lbl2TipoCuenta = new javax.swing.JLabel();
        lblSaldoTotal = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbxCreditos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblDeudaCredito = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCuotaCredito = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFechaPagoCredito = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblCuotasRestantes = new javax.swing.JLabel();
        tbxMontoCredito = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbxCuotasCredito = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnSolicitarCredito = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnPagarCredito = new javax.swing.JButton();
        panelTDC = new javax.swing.JPanel();
        cbxTDC = new javax.swing.JComboBox<>();
        tbxMontoSolicitarTDC = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbxCuotasTDC = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnSolicitarAdelantoTDC = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        btnSolicitarTDC = new javax.swing.JButton();
        tbxMontoDeseadoTDC = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        btnPagarTDC = new javax.swing.JButton();
        planoTarjeta = new javax.swing.JPanel();
        lblNroTarjeta4 = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        lblNombreTarjeta = new javax.swing.JLabel();
        lblNroTarjeta3 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblNroTarjeta2 = new javax.swing.JLabel();
        lblNroTarjeta1 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblLimiteTDC = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblCuotaTDC = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblFechaPagoTDC = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblCuotasRestantesTDC = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblDeudaTDC = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxCdt = new javax.swing.JComboBox<>();
        panelCobroCdt = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblMontoCobrarCdt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDiasRestantesCdt = new javax.swing.JLabel();
        btnCobrarCdt = new javax.swing.JButton();
        panelSolicitudCdt = new javax.swing.JPanel();
        tbxMontoCdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxPlazoCdt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnSolicitarCdt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        jPanel1.setBackground(jTabbedPane2.getBackground());

        tagSaldo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tagSaldo.setForeground(new java.awt.Color(0, 0, 0));
        tagSaldo.setText("Saldo");

        lbl1NroCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl1NroCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lbl1NroCuenta.setText("0000000000");
        lbl1NroCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl1NroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1NroCuentaMouseClicked(evt);
            }
        });

        lbl1Saldo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl1Saldo.setForeground(new java.awt.Color(0, 0, 0));
        lbl1Saldo.setText("0.0");

        bienvenidaUsuario.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        bienvenidaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        bienvenidaUsuario.setText(bienvenida);

        tagNroCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tagNroCuenta.setForeground(new java.awt.Color(0, 0, 0));
        tagNroCuenta.setText("Número de cuenta");

        tagTipoCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tagTipoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        tagTipoCuenta.setText("Tipo de cuenta");

        lbl1TipoCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl1TipoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lbl1TipoCuenta.setText("Ahorros");

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Saldo total");

        lbl2NroCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl2NroCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lbl2NroCuenta.setText("0000000000");
        lbl2NroCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl2NroCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2NroCuentaMouseClicked(evt);
            }
        });

        lbl2Saldo.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl2Saldo.setForeground(new java.awt.Color(0, 0, 0));
        lbl2Saldo.setText("0.0");

        lbl2TipoCuenta.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl2TipoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        lbl2TipoCuenta.setText("Corriente");

        lblSaldoTotal.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblSaldoTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSaldoTotal.setText("0.0");

        lblActualizar.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblActualizar.setForeground(new java.awt.Color(0, 0, 0));
        lblActualizar.setText("Actualizar");
        lblActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(lblSaldoTotal)
                .addGap(281, 281, 281))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2NroCuenta)
                            .addComponent(lbl1NroCuenta)
                            .addComponent(tagNroCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tagSaldo)
                                .addGap(52, 52, 52)
                                .addComponent(tagTipoCuenta))
                            .addComponent(lblActualizar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl2Saldo)
                                    .addComponent(lbl1Saldo))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl1TipoCuenta)
                                    .addComponent(lbl2TipoCuenta))))
                        .addGap(144, 144, 144))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bienvenidaUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bienvenidaUsuario)
                .addGap(35, 35, 35)
                .addComponent(lblActualizar)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagNroCuenta)
                    .addComponent(tagSaldo)
                    .addComponent(tagTipoCuenta))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1NroCuenta)
                    .addComponent(lbl1Saldo)
                    .addComponent(lbl1TipoCuenta))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2NroCuenta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl2TipoCuenta)
                        .addComponent(lbl2Saldo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblSaldoTotal))
                .addGap(39, 39, 39))
        );

        if (cuentasCliente.size()==1)
        lbl2NroCuenta.setText(null);

        jTabbedPane2.addTab("Posición Consolidada", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cbxCreditos.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxCreditos.setForeground(new java.awt.Color(0, 0, 0));
        cbxCreditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCreditosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Deuda");

        lblDeudaCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblDeudaCredito.setForeground(new java.awt.Color(0, 0, 0));
        lblDeudaCredito.setText("jLabel4");

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cuota");

        lblCuotaCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblCuotaCredito.setForeground(new java.awt.Color(0, 0, 0));
        lblCuotaCredito.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fecha de pago");

        lblFechaPagoCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblFechaPagoCredito.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaPagoCredito.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Cuotas restantes");

        lblCuotasRestantes.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblCuotasRestantes.setForeground(new java.awt.Color(0, 0, 0));
        lblCuotasRestantes.setText("jLabel14");

        tbxMontoCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxMontoCredito.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Monto a solicitar");

        cbxCuotasCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxCuotasCredito.setForeground(new java.awt.Color(0, 0, 0));
        cbxCuotasCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24", "36", "48", "60" }));

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Numero de cuotas");

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tasa de interés");

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("2.5%");

        btnSolicitarCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnSolicitarCredito.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitarCredito.setText("Solicitar crédito");
        btnSolicitarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarCreditoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Seleccione su credito");

        btnPagarCredito.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnPagarCredito.setForeground(new java.awt.Color(0, 0, 0));
        btnPagarCredito.setText("Pagar crédito");
        btnPagarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lblCuotasRestantes)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblDeudaCredito)
                            .addComponent(lblCuotaCredito)
                            .addComponent(jLabel9))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblFechaPagoCredito)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPagarCredito)
                        .addGap(55, 55, 55)))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbxCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel16)
                            .addComponent(cbxCuotasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17)
                            .addComponent(btnSolicitarCredito)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbxMontoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxMontoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDeudaCredito)
                                .addComponent(lblFechaPagoCredito))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCuotasCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuotaCredito)
                    .addComponent(lblCuotasRestantes)
                    .addComponent(jLabel17))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSolicitarCredito))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnPagarCredito)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Creditos", jPanel2);

        panelTDC.setBackground(new java.awt.Color(255, 255, 255));
        panelTDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxTDC.setForeground(new java.awt.Color(0, 0, 0));
        cbxTDC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTDCActionPerformed(evt);
            }
        });
        panelTDC.add(cbxTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        tbxMontoSolicitarTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxMontoSolicitarTDC.setForeground(new java.awt.Color(0, 0, 0));
        panelTDC.add(tbxMontoSolicitarTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 89, -1));

        jLabel27.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Monto a solicitar");
        panelTDC.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        cbxCuotasTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxCuotasTDC.setForeground(new java.awt.Color(0, 0, 0));
        cbxCuotasTDC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24", "36", "48", "60" }));
        panelTDC.add(cbxCuotasTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 98, -1));

        jLabel28.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Numero de cuotas");
        panelTDC.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jLabel29.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Tasa de interés");
        panelTDC.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel30.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("2.25%");
        panelTDC.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        btnSolicitarAdelantoTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnSolicitarAdelantoTDC.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitarAdelantoTDC.setText("Solicitar crédito");
        btnSolicitarAdelantoTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarAdelantoTDCActionPerformed(evt);
            }
        });
        panelTDC.add(btnSolicitarAdelantoTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel31.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Seleccione su tarjeta");
        panelTDC.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        btnSolicitarTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnSolicitarTDC.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitarTDC.setText("Solicitar Tarjeta de crédito");
        btnSolicitarTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarTDCActionPerformed(evt);
            }
        });
        panelTDC.add(btnSolicitarTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        tbxMontoDeseadoTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxMontoDeseadoTDC.setForeground(new java.awt.Color(0, 0, 0));
        panelTDC.add(tbxMontoDeseadoTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 89, -1));

        jLabel50.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Monto deseado");
        panelTDC.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        btnPagarTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnPagarTDC.setForeground(new java.awt.Color(0, 0, 0));
        btnPagarTDC.setText("Pagar una cuota");
        btnPagarTDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarTDCActionPerformed(evt);
            }
        });
        panelTDC.add(btnPagarTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        planoTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        planoTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNroTarjeta4.setFont(new java.awt.Font("Halter", 0, 16)); // NOI18N
        lblNroTarjeta4.setForeground(new java.awt.Color(255, 255, 255));
        lblNroTarjeta4.setText("0000");
        planoTarjeta.add(lblNroTarjeta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        lblFechaVencimiento.setFont(new java.awt.Font("Halter", 0, 10)); // NOI18N
        lblFechaVencimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaVencimiento.setText("00/00");
        planoTarjeta.add(lblFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        lblNombreTarjeta.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        lblNombreTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreTarjeta.setText("JOHN DOE");
        planoTarjeta.add(lblNombreTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblNroTarjeta3.setFont(new java.awt.Font("Halter", 0, 16)); // NOI18N
        lblNroTarjeta3.setForeground(new java.awt.Color(255, 255, 255));
        lblNroTarjeta3.setText("0000");
        planoTarjeta.add(lblNroTarjeta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Visa_Logo.png"))); // NOI18N
        planoTarjeta.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 90, 50));

        jLabel48.setBackground(new java.awt.Color(0, 0, 0));
        jLabel48.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText(lblNroTarjeta1.getText());
        planoTarjeta.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel49.setFont(new java.awt.Font("Halter", 0, 10)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("VENCE");
        planoTarjeta.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        lblNroTarjeta2.setFont(new java.awt.Font("Halter", 0, 16)); // NOI18N
        lblNroTarjeta2.setForeground(new java.awt.Color(255, 255, 255));
        lblNroTarjeta2.setText("0000");
        planoTarjeta.add(lblNroTarjeta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        lblNroTarjeta1.setFont(new java.awt.Font("Halter", 0, 16)); // NOI18N
        lblNroTarjeta1.setForeground(new java.awt.Color(255, 255, 255));
        lblNroTarjeta1.setText("0000");
        planoTarjeta.add(lblNroTarjeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel51.setFont(new java.awt.Font("Halter", 0, 5)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("MES/AÑO");
        planoTarjeta.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Halter", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta_de_credito.png"))); // NOI18N
        planoTarjeta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 237));

        jLabel19.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Límite de crédito");
        planoTarjeta.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblLimiteTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblLimiteTDC.setForeground(new java.awt.Color(0, 0, 0));
        lblLimiteTDC.setText("10000000.00");
        planoTarjeta.add(lblLimiteTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel21.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Cuota");
        planoTarjeta.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        lblCuotaTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblCuotaTDC.setForeground(new java.awt.Color(0, 0, 0));
        lblCuotaTDC.setText("1000000.00");
        planoTarjeta.add(lblCuotaTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel23.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Fecha de pago");
        planoTarjeta.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblFechaPagoTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblFechaPagoTDC.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaPagoTDC.setText("25/12/99");
        planoTarjeta.add(lblFechaPagoTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel25.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Cuotas restantes");
        planoTarjeta.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        lblCuotasRestantesTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblCuotasRestantesTDC.setForeground(new java.awt.Color(0, 0, 0));
        lblCuotasRestantesTDC.setText("11");
        planoTarjeta.add(lblCuotasRestantesTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel46.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Deuda");
        planoTarjeta.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        lblDeudaTDC.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblDeudaTDC.setForeground(new java.awt.Color(0, 0, 0));
        lblDeudaTDC.setText("10000000.00");
        planoTarjeta.add(lblDeudaTDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        panelTDC.add(planoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 380));

        jTabbedPane2.addTab("Tarjetas de crédito", panelTDC);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 117, -1, -1));

        cbxCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxCdt.setForeground(new java.awt.Color(0, 0, 0));
        cbxCdt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxCdt.setSelectedIndex(-1);
        cbxCdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCdtActionPerformed(evt);
            }
        });
        jPanel7.add(cbxCdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        panelCobroCdt.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Monto por cobrar");

        lblMontoCobrarCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblMontoCobrarCdt.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoCobrarCdt.setText("jLabel12");

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Dias restantes");

        lblDiasRestantesCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lblDiasRestantesCdt.setForeground(new java.awt.Color(0, 0, 0));
        lblDiasRestantesCdt.setText("jLabel20");

        btnCobrarCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnCobrarCdt.setForeground(new java.awt.Color(0, 0, 0));
        btnCobrarCdt.setText("Cobrar");
        btnCobrarCdt.setEnabled(false);
        btnCobrarCdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarCdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCobroCdtLayout = new javax.swing.GroupLayout(panelCobroCdt);
        panelCobroCdt.setLayout(panelCobroCdtLayout);
        panelCobroCdtLayout.setHorizontalGroup(
            panelCobroCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCobroCdtLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelCobroCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(lblMontoCobrarCdt)
                    .addComponent(jLabel14)
                    .addComponent(lblDiasRestantesCdt)
                    .addComponent(btnCobrarCdt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCobroCdtLayout.setVerticalGroup(
            panelCobroCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCobroCdtLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMontoCobrarCdt)
                .addGap(62, 62, 62)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDiasRestantesCdt)
                .addGap(61, 61, 61)
                .addComponent(btnCobrarCdt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(panelCobroCdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 340));

        panelSolicitudCdt.setBackground(new java.awt.Color(255, 255, 255));

        tbxMontoCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        tbxMontoCdt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Monto");

        cbxPlazoCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cbxPlazoCdt.setForeground(new java.awt.Color(0, 0, 0));
        cbxPlazoCdt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "60", "90", "120", "150", "180", "210", "240", "270", "300", "330", "360" }));

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Plazo");

        btnSolicitarCdt.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        btnSolicitarCdt.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitarCdt.setText("Solicitar CDT");
        btnSolicitarCdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarCdtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSolicitudCdtLayout = new javax.swing.GroupLayout(panelSolicitudCdt);
        panelSolicitudCdt.setLayout(panelSolicitudCdtLayout);
        panelSolicitudCdtLayout.setHorizontalGroup(
            panelSolicitudCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudCdtLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelSolicitudCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tbxMontoCdt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxPlazoCdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnSolicitarCdt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSolicitudCdtLayout.setVerticalGroup(
            panelSolicitudCdtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudCdtLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbxMontoCdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxPlazoCdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSolicitarCdt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(panelSolicitudCdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 220, 340));

        jTabbedPane2.addTab("CDT", jPanel7);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setText("Cerrar sesion");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(688, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarComboCreditos() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < BaseDeDatos.sistema.getCantCreditos(); i++) {
            Object producto = BaseDeDatos.sistema.getCreditos(i);
            if(producto instanceof Creditos credito && credito.getID() == BaseDeDatos.IDsesionIniciada)
                if(credito.getEstado().equals("Activo"))
                modelo.addElement(credito.getMonto());
        }
        modelo.addElement("Solicitar credito");
        cbxCreditos.setModel(modelo);
        cbxCreditos.setSelectedIndex(-1);
    }
    
    private void llenarComboTDC() {
        DefaultComboBoxModel mdlComboTDC = new DefaultComboBoxModel();
        for (int i = 0; i < BaseDeDatos.sistema.getCantTdc(); i++) {
            Object producto = BaseDeDatos.sistema.getTdc(i);
            if(producto instanceof TarjetaDeCredito tdc && tdc.getID()==BaseDeDatos.IDsesionIniciada)
                if(tdc.getEstado().equals("Activo"))
                mdlComboTDC.addElement(tdc.getNumeroDeTarjeta().split(" ")[3]);
        }
        mdlComboTDC.addElement("Solicitar tarjeta");
        cbxTDC.setModel(mdlComboTDC);
        cbxTDC.setSelectedIndex(-1);
    }
    private void cambiarVisibilidadComponentes(Component[] arreglo, boolean estado) {
        for (Component componente : arreglo) {
            componente.setVisible(estado);
        }
    }
    private void labelsPanelCdt() {
       var indiceSeleccionado = cbxCdt.getSelectedIndex();
       var buscador = 0;
       if(indiceSeleccionado == -1) {
           panelSolicitudCdt.setVisible(false);
           panelCobroCdt.setVisible(false);
       }
       else if(cbxCdt.getSelectedItem().equals("Solicitar CDT")) {
           panelSolicitudCdt.setVisible(true);
           panelCobroCdt.setVisible(false);
       }
       else {
           panelSolicitudCdt.setVisible(false);
           panelCobroCdt.setVisible(true);
           for (int i = 0; i < BaseDeDatos.sistema.getCantCdt(); i++) {
                cdtSeleccionado = BaseDeDatos.sistema.getCdt(i);
               if (cdtSeleccionado.getEstado().equals("Activo") && cdtSeleccionado.getID() == clienteSesionIniciada.getID()) {
                   if(indiceSeleccionado==buscador) {
                       lblMontoCobrarCdt.setText(String.format("%.2f",cdtSeleccionado.getMontoARetirar()));
                       lblDiasRestantesCdt.setText(String.valueOf(DAYS.between(LocalDate.now(),cdtSeleccionado.getFechaRetiro())));
                       if(DAYS.between(LocalDate.now(),cdtSeleccionado.getFechaRetiro()) <= 0) {
                           btnCobrarCdt.setEnabled(true);
                       }
                       break;
                   }
                   else
                       buscador++;
               }      
           }
       }
    }
    private void labelsPanelTDC() {
        int indiceSeleccionado = cbxTDC.getSelectedIndex();
        int buscador = 0;
        Component[] componentesSolicitud = {btnSolicitarTDC, tbxMontoDeseadoTDC, jLabel50};
        Component[] componentesFueraPlano = {tbxMontoSolicitarTDC, jLabel27, cbxCuotasTDC, jLabel28, jLabel29, 
            btnSolicitarAdelantoTDC, btnPagarTDC, jLabel30};
        if(indiceSeleccionado == -1) {
            cambiarVisibilidadComponentes(componentesSolicitud, false);
            cambiarVisibilidadComponentes(componentesFueraPlano, false);
            planoTarjeta.setVisible(false);
        }
        else if(cbxTDC.getItemAt(indiceSeleccionado).equals("Solicitar tarjeta")) {
            cambiarVisibilidadComponentes(componentesFueraPlano, false);
            cambiarVisibilidadComponentes(componentesSolicitud, true);
            planoTarjeta.setVisible(false);
        }
        else if (indiceSeleccionado >=0) {
            cambiarVisibilidadComponentes(componentesSolicitud, false);
            cambiarVisibilidadComponentes(componentesFueraPlano, true);
            planoTarjeta.setVisible(true);
           for (int i = 0; i < BaseDeDatos.sistema.getCantTdc(); i++) {
               Object producto = BaseDeDatos.sistema.getTdc(i);
               if(producto instanceof TarjetaDeCredito tdc && tdc.getEstado().equals("Activo") && tdc.getID() ==BaseDeDatos.IDsesionIniciada){
                   if (indiceSeleccionado == buscador) {
                   String[] numeroTarjeta = tdc.getNumeroDeTarjeta().split(" ");
                   lblNroTarjeta1.setText(numeroTarjeta[0]);
                   lblNroTarjeta2.setText(numeroTarjeta[1]);
                   lblNroTarjeta3.setText(numeroTarjeta[2]);
                   lblNroTarjeta4.setText(numeroTarjeta[3]);
                   lblNombreTarjeta.setText(clienteSesionIniciada.getNombre());
                   lblFechaVencimiento.setText(tdc.getFechaDeVencimiento().format(DateTimeFormatter.ofPattern("MM/yy")));
                   lblDeudaTDC.setText(String.format("%.2f", tdc.getMontoAdeudado()).replace(",", "."));
                   lblCuotaTDC.setText(String.format("%.2f", tdc.getValorCuota()).replace(",", "."));
                   lblCuotasRestantesTDC.setText(String.valueOf(tdc.getNroCuotasAdeudadas()));
                   lblFechaPagoTDC.setText(String.valueOf(tdc.getFechaProximoPagoTexto()));
                   lblLimiteTDC.setText(String.format("%.2f",tdc.getMontoTotal()).replace(",", "."));
                   if(tdc.getNroCuotasAdeudadas()==0) {
                       btnPagarTDC.setEnabled(false);
                   }
                   else
                       btnPagarTDC.setEnabled(true);
                   break;
                   }
               else if(producto instanceof TarjetaDeCredito && tdc.getID() == BaseDeDatos.IDsesionIniciada && indiceSeleccionado!=buscador)
                   buscador++;
               }
           } 
        }
        if(Float.parseFloat(lblDeudaTDC.getText())>500) {
            btnSolicitarAdelantoTDC.setEnabled(false);
        }
        else
            btnSolicitarAdelantoTDC.setEnabled(true);
        
        
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        BaseDeDatos.guardarCambios();
        this.setVisible(false);
        new InicioSesion().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       jLabel2.setForeground(Color.red);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseExited

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        actualizarVentana();
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lbl2NroCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2NroCuentaMouseClicked
        if(lbl2NroCuenta.getText().equals("Haga clic si desea pedir una nueva cuenta")) {
            Cuentas segundaCuenta = new Cuentas();
            segundaCuenta.setID(clienteSesionIniciada.getID());
            segundaCuenta.crearNumeroCuenta();
            segundaCuenta.setSaldo(0);
            segundaCuenta.setEstado("Pendiente");
            tipoSegundaCuenta(segundaCuenta);
            BaseDeDatos.sistema.setCuentas(segundaCuenta);
            actualizarVentana();
            BaseDeDatos.guardarCambios();
        }
        else if (lbl2NroCuenta.getText().equals("Su cuenta se encuentra pendiente por aprobación")) {
        }
        else {
            BaseDeDatos.nroCuentaEnUso = lbl2NroCuenta.getText();
            new ConsignarRetirarCuenta().setVisible(true);
        }
    }//GEN-LAST:event_lbl2NroCuentaMouseClicked

    private void lbl1NroCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1NroCuentaMouseClicked
        new ConsignarRetirarCuenta().setVisible(true);
        BaseDeDatos.nroCuentaEnUso = lbl1NroCuenta.getText();
    }//GEN-LAST:event_lbl1NroCuentaMouseClicked

    private void cbxTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTDCActionPerformed
        labelsPanelTDC();
    }//GEN-LAST:event_cbxTDCActionPerformed

    private void btnSolicitarTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarTDCActionPerformed
        TarjetaDeCredito tdc = new TarjetaDeCredito();
        tdc.setMontoTotal(Float.parseFloat(tbxMontoDeseadoTDC.getText()));
        tdc.setEstado("Pendiente");
        tdc.setFechaDeVencimiento(LocalDate.now().plusYears(10));
        tdc.generarCVV();
        tdc.generarNumeroTarjeta();
        tdc.setID(clienteSesionIniciada.getID());
        BaseDeDatos.sistema.setTdc(tdc);
        tbxMontoDeseadoTDC.setText(null);
        cbxTDC.setSelectedIndex(-1);
    }//GEN-LAST:event_btnSolicitarTDCActionPerformed

    private void btnSolicitarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarCreditoActionPerformed
        Creditos credito = new Creditos();
        credito.setMonto(Float.parseFloat(tbxMontoCredito.getText()));
        credito.setEstado("Pendiente");
        credito.setTasaDeInteres((float)2.25);
        credito.setCuotasAdeudadas((cbxCuotasCredito.getSelectedIndex()+1)*12);
        credito.setFechaProximoPago(LocalDate.now().plusMonths(1));
        credito.calcularCuota();
        credito.setID(clienteSesionIniciada.getID());
        BaseDeDatos.sistema.setCreditos(credito);
        cbxCreditos.setSelectedIndex(-1);
    }//GEN-LAST:event_btnSolicitarCreditoActionPerformed

    private void btnSolicitarAdelantoTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarAdelantoTDCActionPerformed
        int indiceSeleccionado = cbxTDC.getSelectedIndex();
        int buscador = 0;
        
         for (int i = 0; i < BaseDeDatos.sistema.getCantCuentas(); i++) {
            Cuentas cuenta = BaseDeDatos.sistema.getCuentas(i);
                if(cuenta.getNumeroCuenta().equals(lbl1NroCuenta.getText())) {
                    cuenta.consignar(Float.parseFloat(tbxMontoSolicitarTDC.getText()));
                }
         }
        for (int i = 0; i < BaseDeDatos.sistema.getCantTdc(); i++) {
            TarjetaDeCredito tdc = BaseDeDatos.sistema.getTdc(i);
            if(tdc.getID() == clienteSesionIniciada.getID()) {
                if(tdc.getEstado().equals("Activo")) {
                    if(indiceSeleccionado == buscador) {
                        if(tdc.getMontoTotal()>=Float.parseFloat(tbxMontoSolicitarTDC.getText())){
                            tdc.setMontoAdeudado(Float.parseFloat(tbxMontoSolicitarTDC.getText()));
                            tdc.setNroCuotasAdeudadas((cbxCuotasTDC.getSelectedIndex()+1)*12);
                            tdc.setValorCuota((cbxCuotasTDC.getSelectedIndex()+1)*12);
                            tdc.setFechaProximoPago(LocalDate.now().plusMonths(1));
                            btnSolicitarAdelantoTDC.setEnabled(false);
                            cbxCuotasTDC.setSelectedIndex(0);
                            tbxMontoSolicitarTDC.setText(null);
                            labelsPanelTDC();
                            BaseDeDatos.guardarCambios();
                            break;
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "No puede solicitar un monto mayor a su límite");
                        }   
                    }
                    else
                        buscador++;
                }
            }
        }
    }//GEN-LAST:event_btnSolicitarAdelantoTDCActionPerformed

    private void btnPagarTDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarTDCActionPerformed
        int indiceSeleccionado = cbxTDC.getSelectedIndex();
        int buscador = 0;
        
        for (int i = 0; i < BaseDeDatos.sistema.getCantCuentas(); i++) {
            Cuentas cuenta = BaseDeDatos.sistema.getCuentas(i);
            if(cuenta.getID() == clienteSesionIniciada.getID()) {
                if(cuenta.getNumeroCuenta().equals(lbl1NroCuenta.getText())) {
                    if(cuenta.getSaldo() > Float.parseFloat(lblCuotaTDC.getText())) {
                        cuenta.retirar(Float.parseFloat(lblCuotaTDC.getText()));
                        for (int j = 0; j < BaseDeDatos.sistema.getCantTdc(); j++) {
                            TarjetaDeCredito tdc = BaseDeDatos.sistema.getTdc(j);
                            if(tdc.getID()==clienteSesionIniciada.getID() && tdc.getEstado().equals("Activo")) {
                                if(indiceSeleccionado == buscador) {
                                    tdc.pagoCuota(Float.parseFloat(lblCuotaTDC.getText()));
                                    tdc.setFechaProximoPago(tdc.getFechaProximoPago().plusMonths(1));
                                    labelsPanelTDC();
                                    BaseDeDatos.guardarCambios();
                                    break;
                                }
                                else
                                    buscador++;
                            } 
                        }
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Fondos insuficientes");
                }
            }
        }
    }//GEN-LAST:event_btnPagarTDCActionPerformed

    private void cbxCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCreditosActionPerformed
        labelsPanelCreditos();
    }//GEN-LAST:event_cbxCreditosActionPerformed

    private void labelsPanelCreditos() {
        int indiceSeleccionado = cbxCreditos.getSelectedIndex();
        int buscador = 0;
        Component[] componentesSolicitudCredito = {tbxMontoCredito, jLabel15, cbxCuotasCredito, jLabel16,
            jLabel5, jLabel17, btnSolicitarCredito};
        Component[] componentesCreditoSeleccionado = {jLabel3, lblDeudaCredito, jLabel9, lblCuotaCredito, jLabel11,lblFechaPagoCredito,
            jLabel13,lblCuotasRestantes,btnPagarCredito};
        if(cbxCreditos.getSelectedIndex() == -1) {
            cambiarVisibilidadComponentes(componentesSolicitudCredito, false);
            cambiarVisibilidadComponentes(componentesCreditoSeleccionado, false);
        }
        else if(cbxCreditos.getSelectedItem().equals("Solicitar credito")) {
            cambiarVisibilidadComponentes(componentesSolicitudCredito, true);
            cambiarVisibilidadComponentes(componentesCreditoSeleccionado, false);
        }
        else {
            cambiarVisibilidadComponentes(componentesSolicitudCredito, false);
            cambiarVisibilidadComponentes(componentesCreditoSeleccionado, true);
            for (int i = 0; i < BaseDeDatos.sistema.getCantCreditos(); i++) {
                Creditos credito = BaseDeDatos.sistema.getCreditos(i);
                if(credito.getID() == clienteSesionIniciada.getID() && credito.getEstado().equals("Activo")) {
                    if(buscador == indiceSeleccionado) {
                        lblDeudaCredito.setText(String.format("%.2f",credito.getMontoAdeudado()));
                        lblFechaPagoCredito.setText(String.valueOf(credito.getFechaProximoPago("Para label")));
                        lblCuotaCredito.setText(String.valueOf(credito.getValorCuota()));
                        lblCuotasRestantes.setText(String.valueOf(credito.getCuotasAdeudadas()));
                        break;
                    }
                    else  {
                    buscador++;
                    }
                }
            }
        }
    }

    private void btnPagarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarCreditoActionPerformed
        int indiceSeleccionado = cbxCreditos.getSelectedIndex();
        int buscador = 0;
        
        for (int i = 0; i < BaseDeDatos.sistema.getCantCuentas(); i++) {
            Cuentas cuenta = BaseDeDatos.sistema.getCuentas(i);
            if(cuenta.getID()==clienteSesionIniciada.getID()) {
                if(cuenta.getNumeroCuenta().equals(lbl1NroCuenta.getText())) {
                    if(cuenta.getSaldo() > Float.parseFloat(lblCuotaCredito.getText())) {
                        cuenta.retirar(Float.parseFloat(lblCuotaCredito.getText()));
                        for (int j = 0; j < BaseDeDatos.sistema.getCantCreditos(); j++) {
                            Creditos credito = BaseDeDatos.sistema.getCreditos(j);
                            if(credito.getID() == clienteSesionIniciada.getID()&& credito.getEstado().equals("Activo")) {
                                if(indiceSeleccionado == buscador) {
                                    credito.pagoCuota(Float.parseFloat(lblCuotaCredito.getText()));
                                    credito.setFechaProximoPago(credito.getFechaProximoPago().plusMonths(1));
                                    if(credito.getCuotasAdeudadas()<=50) {
                                        credito.setEstado("Pagado");
                                        llenarComboCreditos();
                                    }
                                    BaseDeDatos.guardarCambios();
                                    break;
                                }
                                else
                                    buscador++;
                            } 
                        }
                        labelsPanelCreditos();
                        break;
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Fondos insuficientes");
                }
            }
        }
    }//GEN-LAST:event_btnPagarCreditoActionPerformed

    private void btnSolicitarCdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarCdtActionPerformed
        if(cuentasCliente.get(0).getSaldo() >= Float.parseFloat(tbxMontoCdt.getText())) {
            cuentasCliente.get(0).retirar(Float.parseFloat(tbxMontoCdt.getText()));
            Cdt cdt = new Cdt();
            cdt.setEstado("Pendiente");
            cdt.setID(clienteSesionIniciada.getID());
            cdt.setMontoDepositado(Float.parseFloat(tbxMontoCdt.getText()));
            cdt.setPlazo((cbxPlazoCdt.getSelectedIndex()+1)*30);
            cdt.calculoMontoFinal();
            cdt.setFechaRetiro(LocalDate.now().plusDays(cdt.getPlazo()));
            BaseDeDatos.sistema.setCdt(cdt);
            BaseDeDatos.guardarCambios();
        }
        else
            JOptionPane.showMessageDialog(this, "Fondos insuficientes");
        cbxCdt.setSelectedIndex(-1);
        
    }//GEN-LAST:event_btnSolicitarCdtActionPerformed

    private void cbxCdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCdtActionPerformed
        labelsPanelCdt();
    }//GEN-LAST:event_cbxCdtActionPerformed

    private void btnCobrarCdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarCdtActionPerformed
        cuentasCliente.get(0).consignar(cdtSeleccionado.getMontoARetirar());
        cdtSeleccionado.setEstado("Completado");
        llenarComboCdt();
        BaseDeDatos.guardarCambios();
    }//GEN-LAST:event_btnCobrarCdtActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        BaseDeDatos.guardarCambios();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void tipoSegundaCuenta(Cuentas segundaCuenta) {
        if(lbl1TipoCuenta.getText().equals("Ahorros"))
            segundaCuenta.setTipoDeCuenta("Corriente");
        else
            segundaCuenta.setTipoDeCuenta("Ahorros");
    }

    public String pronombreSaludo() {
        if (clienteSesionIniciada.getSexo().equals("Masculino"))
            return "Sr. ";
        else
            return "Sra. ";
    }
    
    public final void actualizarVentana() {
        buscarCuentas();
        llenarEtiquetasPosicionConsolidado();
        mostrarSaldoTotal();
    }
    
    public void llenarEtiquetasTarjetaDeCredito() {
        
    }
    
    public void mostrarSaldoTotal() {
        float saldo1= Float.parseFloat(lbl1Saldo.getText());
        float saldo2;
        boolean isSaldo2= lbl2Saldo.getText() == null;
        float salida;
        if(isSaldo2) 
            salida = saldo1;
        else {
            saldo2= Float.parseFloat(lbl2Saldo.getText());
            salida = saldo1+saldo2;
        }
            
        lblSaldoTotal.setText(String.format("%.2f\n",salida).replace(",", "."));
    }
    public void buscarCuentas() {
        cuentasCliente.clear();
        for (int i = 0; i < BaseDeDatos.sistema.getCantCuentas(); i++) {
            if (BaseDeDatos.sistema.getCuentas(i).getID() == BaseDeDatos.IDsesionIniciada)
                cuentasCliente.add(BaseDeDatos.sistema.getCuentas(i));
        }
    }
    
    public void llenarEtiquetasPosicionConsolidado() {
       javax.swing.JLabel[] etiquetasCuenta1 = {lbl1NroCuenta, lbl1Saldo,lbl1TipoCuenta};
       javax.swing.JLabel[] etiquetasCuenta2 = {lbl2NroCuenta, lbl2Saldo, lbl2TipoCuenta};
       javax.swing.JLabel[][] etiquetas = {etiquetasCuenta1, etiquetasCuenta2};
        for (int i = 0; i < cuentasCliente.size(); i++) {
            etiquetas[i][0].setText(cuentasCliente.get(i).getNumeroCuenta());
            etiquetas[i][1].setText(String.format("%.2f\n", cuentasCliente.get(i).getSaldo()).replace(",", "."));
            etiquetas[i][2].setText(cuentasCliente.get(i).getTipoDeCuenta());
        }
        if (cuentasCliente.size()==1) {
            limpiarEtiquetas(etiquetasCuenta2);
            lbl2NroCuenta.setText("Haga clic si desea pedir una nueva cuenta");
            lbl2NroCuenta.setForeground(Color.black);
        }
        else if (cuentasCliente.get(1).getEstado().equals("Pendiente")) {
            limpiarEtiquetas(etiquetasCuenta2);
            lbl2NroCuenta.setText("Su cuenta se encuentra pendiente");
            lbl2NroCuenta.setForeground(Color.black);
        }
    }

    private void limpiarEtiquetas(JLabel[] etiquetasCuenta2) {
        for (JLabel etiquetasCuenta21 : etiquetasCuenta2) {
            etiquetasCuenta21.setForeground(Color.white);
        }
    }
    
    private void llenarComboCdt() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < BaseDeDatos.sistema.getCantCdt(); i++) {
            Object producto = BaseDeDatos.sistema.getCdt(i);
            if(producto instanceof Cdt cdt && cdt.getID() == BaseDeDatos.IDsesionIniciada)
                if(cdt.getEstado().equals("Activo"))
                modelo.addElement(cdt.getFechaRetiro().toString());
        }
        modelo.addElement("Solicitar CDT");
        cbxCdt.setModel(modelo);
        cbxCdt.setSelectedIndex(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidaUsuario;
    private javax.swing.JButton btnCobrarCdt;
    private javax.swing.JButton btnPagarCredito;
    private javax.swing.JButton btnPagarTDC;
    private javax.swing.JButton btnSolicitarAdelantoTDC;
    private javax.swing.JButton btnSolicitarCdt;
    private javax.swing.JButton btnSolicitarCredito;
    private javax.swing.JButton btnSolicitarTDC;
    private javax.swing.JComboBox<String> cbxCdt;
    private javax.swing.JComboBox<String> cbxCreditos;
    private javax.swing.JComboBox<String> cbxCuotasCredito;
    private javax.swing.JComboBox<String> cbxCuotasTDC;
    private javax.swing.JComboBox<String> cbxPlazoCdt;
    private javax.swing.JComboBox<String> cbxTDC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl1NroCuenta;
    private javax.swing.JLabel lbl1Saldo;
    private javax.swing.JLabel lbl1TipoCuenta;
    private javax.swing.JLabel lbl2NroCuenta;
    private javax.swing.JLabel lbl2Saldo;
    private javax.swing.JLabel lbl2TipoCuenta;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblCuotaCredito;
    private javax.swing.JLabel lblCuotaTDC;
    private javax.swing.JLabel lblCuotasRestantes;
    private javax.swing.JLabel lblCuotasRestantesTDC;
    private javax.swing.JLabel lblDeudaCredito;
    private javax.swing.JLabel lblDeudaTDC;
    private javax.swing.JLabel lblDiasRestantesCdt;
    private javax.swing.JLabel lblFechaPagoCredito;
    private javax.swing.JLabel lblFechaPagoTDC;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblLimiteTDC;
    private javax.swing.JLabel lblMontoCobrarCdt;
    private javax.swing.JLabel lblNombreTarjeta;
    private javax.swing.JLabel lblNroTarjeta1;
    private javax.swing.JLabel lblNroTarjeta2;
    private javax.swing.JLabel lblNroTarjeta3;
    private javax.swing.JLabel lblNroTarjeta4;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JPanel panelCobroCdt;
    private javax.swing.JPanel panelSolicitudCdt;
    private javax.swing.JPanel panelTDC;
    private javax.swing.JPanel planoTarjeta;
    private javax.swing.JLabel tagNroCuenta;
    private javax.swing.JLabel tagSaldo;
    private javax.swing.JLabel tagTipoCuenta;
    private javax.swing.JTextField tbxMontoCdt;
    private javax.swing.JTextField tbxMontoCredito;
    private javax.swing.JTextField tbxMontoDeseadoTDC;
    private javax.swing.JTextField tbxMontoSolicitarTDC;
    // End of variables declaration//GEN-END:variables
}
